#!/bin/sh
set -e

DOTFILES="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$HOME/.config"

link_dir() {
    src="$DOTFILES/$1"
    dst="$CONFIG/$2"
    mkdir -p "$(dirname "$dst")"
    rm -rf "$dst"
    ln -s "$src" "$dst"
    echo "  linked $dst"
}

echo "Installing labwc-quickshell (Pillbox)..."

link_dir labwc       labwc
link_dir quickshell  quickshell
link_dir pillbox     pillbox
link_dir kitty       kitty
link_dir matugen     matugen
link_dir scripts     scripts

# Google integration scripts — symlinked so repo edits take effect immediately.
# All three share the same OAuth token at ~/.config/gcal-quickshell/token.json.
# Run `gcal-fetch --auth` once after install to complete the consent flow.
ln -snf "$DOTFILES/helper/calendar/gcal_fetch.py"    "$HOME/.local/bin/gcal-fetch"
echo "  linked gcal-fetch → ~/.local/bin"
ln -snf "$DOTFILES/helper/tasks/gtask_fetch.py"      "$HOME/.local/bin/gtask-fetch"
echo "  linked gtask-fetch → ~/.local/bin"
ln -snf "$DOTFILES/helper/google_auth_notify.sh"     "$HOME/.local/bin/google-auth-notify"
chmod +x "$DOTFILES/helper/google_auth_notify.sh"
echo "  linked google-auth-notify → ~/.local/bin"

ln -snf "$DOTFILES/helper/weather/weather_fetch.py" "$HOME/.local/bin/weather-fetch"
echo "  linked weather-fetch → ~/.local/bin"

ln -snf "$DOTFILES/helper/kitty/kitty-theme.sh" "$HOME/.local/bin/kitty-theme"
chmod +x "$DOTFILES/helper/kitty/kitty-theme.sh"
echo "  linked kitty-theme → ~/.local/bin"

ln -snf "$DOTFILES/helper/screenshot/pillbox-screenshot"         "$HOME/.local/bin/pillbox-screenshot"
echo "  linked pillbox-screenshot → ~/.local/bin"
ln -snf "$DOTFILES/helper/screenshot/pillbox-screenshot-region" "$HOME/.local/bin/pillbox-screenshot-region"
echo "  linked pillbox-screenshot-region → ~/.local/bin"
ln -snf "$DOTFILES/helper/screenrec/pillbox-screenrec"          "$HOME/.local/bin/pillbox-screenrec"
echo "  linked pillbox-screenrec → ~/.local/bin"
ln -snf "$DOTFILES/helper/screenrec/pillbox-screenrec-region"   "$HOME/.local/bin/pillbox-screenrec-region"
echo "  linked pillbox-screenrec-region → ~/.local/bin"
ln -snf "$DOTFILES/helper/screenrec/pillbox-screenrec-e"        "$HOME/.local/bin/pillbox-screenrec-e"
echo "  linked pillbox-screenrec-e → ~/.local/bin"
ln -snf "$DOTFILES/helper/screenrec/pillbox-screenrec-saved"    "$HOME/.local/bin/pillbox-screenrec-saved"
echo "  linked pillbox-screenrec-saved → ~/.local/bin"
ln -snf "$DOTFILES/helper/sysmon/pillbox-sysmon"               "$HOME/.local/bin/pillbox-sysmon"
echo "  linked pillbox-sysmon → ~/.local/bin"

# Kvantum: symlink theme selector + create output dir for matugen-generated theme files
mkdir -p "$HOME/.config/Kvantum/Pillbox"
ln -snf "$DOTFILES/kvantum/kvantum.kvconfig" "$HOME/.config/Kvantum/kvantum.kvconfig"
echo "  linked kvantum.kvconfig → Pillbox theme"

# qt6ct: switch to Kvantum style + Pillbox color scheme (generated by matugen)
QT6CT_CONF="$HOME/.config/qt6ct/qt6ct.conf"
mkdir -p "$HOME/.config/qt6ct/colors"
if [ -f "$QT6CT_CONF" ]; then
    sed -i 's/^style=.*/style=kvantum/' "$QT6CT_CONF"
    sed -i 's|^custom_palette=.*|custom_palette=true|' "$QT6CT_CONF"
    sed -i "s|^color_scheme_path=.*|color_scheme_path=$HOME/.config/qt6ct/colors/Pillbox.conf|" "$QT6CT_CONF"
    echo "  patched qt6ct: style=kvantum, color_scheme=Pillbox"
else
    echo "  qt6ct not found at $QT6CT_CONF — run qt6ct once first, then re-run install.sh"
fi


# Ensure ~/.local/bin is in labwc/environment PATH so quickshell can find gcal-fetch.
# labwc reads this file before launching child processes; the user's shell PATH is not inherited.
LOCAL_BIN="$HOME/.local/bin"
ENV_FILE="$DOTFILES/labwc/environment"
if ! grep -q "^PATH=.*$LOCAL_BIN" "$ENV_FILE" 2>/dev/null; then
    printf "\n  ~/.local/bin is not in labwc/environment PATH.\n"
    printf "  quickshell needs this to find gcal-fetch/gtask-fetch/weather-fetch/google-auth-notify at runtime.\n"
    printf "  Add it automatically? [Y/n] "
    read -r _answer
    if [ "${_answer:-y}" != "n" ] && [ "${_answer:-y}" != "N" ]; then
        if grep -q "^PATH=" "$ENV_FILE" 2>/dev/null; then
            sed -i "s|^PATH=|PATH=$LOCAL_BIN:|" "$ENV_FILE"
        else
            printf "PATH=%s:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl\n" "$LOCAL_BIN" >> "$ENV_FILE"
        fi
        echo "  added ~/.local/bin to PATH in labwc/environment"
    else
        echo "  skipped — add PATH=~/.local/bin:\$PATH to labwc/environment manually or gcal-fetch/weather-fetch won't be found"
    fi
fi

# labwc menu icons — white variants installed to hicolor so labwc finds them by name
HICOLOR="$HOME/.local/share/icons/hicolor"
mkdir -p "$HICOLOR/22x22/apps" "$HICOLOR/22x22/actions"
ln -snf "$DOTFILES/labwc/icons/menu-web-browser.svg" "$HICOLOR/22x22/apps/menu-web-browser.svg"
ln -snf "$DOTFILES/labwc/icons/menu-run.svg"         "$HICOLOR/22x22/actions/menu-run.svg"
ln -snf "$DOTFILES/labwc/icons/menu-terminal.svg"    "$HICOLOR/22x22/apps/menu-terminal.svg"
ln -snf "$DOTFILES/labwc/icons/menu-logout.svg"      "$HICOLOR/22x22/actions/menu-logout.svg"
ln -snf "$DOTFILES/labwc/icons/menu-steam.svg"       "$HICOLOR/22x22/apps/menu-steam.svg"
echo "  linked labwc menu icons → hicolor"

echo ""
echo "Setting up media directories..."
PICTURES_DIR="$(xdg-user-dir PICTURES 2>/dev/null || echo "$HOME")"
VIDEOS_DIR="$(xdg-user-dir VIDEOS 2>/dev/null || echo "$HOME")"

if [ "$PICTURES_DIR" = "$HOME" ] && [ "$VIDEOS_DIR" = "$HOME" ]; then
    # xdg-user-dirs not configured — fall back to ~/Pillbox
    PILLBOX_MEDIA_BASE="$HOME/Pillbox"
    if [ ! -d "$PILLBOX_MEDIA_BASE" ]; then
        echo "  xdg-user-dirs not configured and $PILLBOX_MEDIA_BASE not found — creating it"
    else
        echo "  xdg-user-dirs not configured — using existing $PILLBOX_MEDIA_BASE"
    fi
    SCREENSHOTS_DIR="$PILLBOX_MEDIA_BASE/Screenshots"
    RECORDINGS_DIR="$PILLBOX_MEDIA_BASE/Recordings"
    REPLAYS_DIR="$PILLBOX_MEDIA_BASE/Recordings/Replays"
else
    SCREENSHOTS_DIR="$PICTURES_DIR/Screenshots"
    RECORDINGS_DIR="$VIDEOS_DIR/Recordings"
    REPLAYS_DIR="$VIDEOS_DIR/Recordings/Replays"
fi

for d in "$SCREENSHOTS_DIR" "$RECORDINGS_DIR" "$REPLAYS_DIR"; do
    if [ ! -d "$d" ]; then
        mkdir -p "$d"
        echo "  created $d"
    else
        echo "  exists  $d"
    fi
done
MEDIA_LINK_DIR="$DOTFILES/pillbox/media"
mkdir -p "$MEDIA_LINK_DIR"
ln -snf "$SCREENSHOTS_DIR" "$MEDIA_LINK_DIR/Screenshots"
ln -snf "$RECORDINGS_DIR"  "$MEDIA_LINK_DIR/Recordings"
ln -snf "$REPLAYS_DIR"     "$MEDIA_LINK_DIR/Replays"
echo "  linked pillbox/media/ → media dirs"

echo ""
echo "Done."
echo "  Note: ensure ~/.local/bin is in your PATH for gcal-fetch/gtask-fetch."
echo "  Note: gcal-fetch and gtask-fetch need ~/.config/gcal-quickshell/credentials.json (Google OAuth client, not in this repo)."
echo "        Run 'gcal-fetch --auth' once to complete the consent flow (covers both Calendar and Tasks)."
echo "  Note: Pillbox FIFO lives at ~/.local/share/pillbox/pillbox.fifo — created automatically on first run."
echo "        labwc keybinds should write commands to that path (e.g. echo 'showTime' > ~/.local/share/pillbox/pillbox.fifo)."
